name: ROS

on:
  push:
    branches: [melodic]
  workflow_dispatch:
    
jobs:
  test:
    name: test_${{ matrix.tests }}
    runs-on: ubuntu-latest
    container: athackst/ros:melodic-gazebo
    strategy:
      fail-fast: false
      matrix:
          tests: [test_level_1_functional_arch, test_qa_reception, test_models_paper]
    steps:
      - uses: actions/checkout@v2
      - name: "Get workspace"
        run: |
          if [ -f ros_melodic.rosinstall ]; then
            wstool init src ros_melodic.rosinstall
          fi
      - name: "Get dependencies"
        run: |
          sudo apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -y --rosdistro=melodic --skip-keys="abb_rws_interface"
      - name: "Build"
        run: |
          catkin build 
        continue-on-error: false
      - name: "Run Tests"
        run: |
          rostest mros1_reasoner ${{ matrix.tests }}.test
