name: ROS

on:
  push:
    branches: [melodic]
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    container: athackst/ros:melodic-gazebo
    steps:
      - uses: actions/checkout@v2
      - name: "Get workspace"
        run: |
          if [ -f src/ros_melodic.rosinstall ]; then
            wstool init src ros_melodic.rosinstall
          fi
      - name: "Get dependencies"
        run: |
          sudo apt-get update
          rosdep update
          rosdep install --from-paths ./src -i -y --rosdistro melodic --skip-keys="abb_rws_interface"
      - name: "Build"
        run: |
          catkin build 
        continue-on-error: true
      - name: "Test"
        run: |
          catkin_make run_tests
  lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    container: athackst/ros:melodic-gazebo
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, uncrustify, lint_cmake, xmllint, flake8, pep257]
    steps:
      - uses: actions/checkout@v2
      - name: "Get workspace"
        run: |
          if [ -f src/ros2.repos ]; then
            wstool init src ros_melodic.rosinstall
          fi
      - name: "run linter"
        run: |
          ament_${{ matrix.linter }} src/
