name: ROS

on:
  push:
    branches: [melodic]
  workflow_dispatch:
    
jobs:
  test:
    name: test_${{ matrix.tests }}
    runs-on: ubuntu-20.04
    container: athackst/ros:melodic-gazebo
    strategy:
      fail-fast: false
      matrix:
          tests: [test_level_1_functional_arch, test_qa_reception, test_models_paper]
    steps:
      - uses: actions/checkout@v2
      - name: "Get workspace"
        run: |
            wstool init src https://raw.githubusercontent.com/rosin-project/metacontrol_experiments/master/metacontrol_experiments.rosinstall
      - name: "Get dependencies"
        run: |
          sudo apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -y --rosdistro=melodic --skip-keys="abb_rws_interface"
      - name: "Build"
        run: |
          catkin build
      - name: "Run Tests"
        run: |
          bash -ic "source devel/setup.bash; rostest mros1_reasoner ${{ matrix.tests }}.test"
