name: ROS

on:
  push:
    branches: [melodic]
  workflow_dispatch:
    
jobs:
  test:
    name: test_${{ matrix.profile }}_${{ matrix.init }}_${{ matrix.goal }}
    runs-on: ubuntu-20.04
    container: athackst/ros:melodic-gazebo
    strategy:
      fail-fast: false
      matrix:
          profile: ["f1_v1_r1"]
          init: ["1", "2"]
          goal: ["4", "5"]
    steps:
      - uses: actions/checkout@v2
      - name: "Get workspace"
        run: |
            wstool init src https://raw.githubusercontent.com/rosin-project/metacontrol_experiments/master/metacontrol_experiments.rosinstall
      - name: "Get dependencies"
        run: |
          sudo apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -y --rosdistro=melodic --skip-keys="abb_rws_interface"
      - name: "Build"
        run: |
          catkin build
      - name: "Run Scripts"
        run: |
          bash -ic "source devel/setup.bash; roscd metacontrol_experiments; ps aux | grep ros | grep -v grep; ./run_single_sim.sh -i ${{ matrix.init }} -g ${{ matrix.goal }} -n ${{ matrix.profile }}"
