name: ROS

on:
  push:
    branches: [melodic]
  workflow_dispatch:
    
jobs:
  test:
    name: test_${{ matrix.profile }}_${{ matrix.init }}_${{ matrix.goal }}
    runs-on: ubuntu-20.04
    container: osrf/ros:melodic-desktop-full-bionic
    strategy:
      fail-fast: false
      matrix:
          profile: ["f1_v1_r1","f1_v1_r2","f1_v1_r3"]
          init: ["1", "2", "3"]
          goal: ["1", "2", "3"]
    env:
      CCACHE_DIR: "/home/runner/.ccache"
      LOG_DIR: "/github/home/metacontrol_ws/src/metacontrol_experiments/data"
      LOG_FILENAME: "log_Metacontrol_sim_"
    steps:
      - name: "Get workspace"
        run: |
            mkdir -p ~/metacontrol_ws/src
            cd ~/metacontrol_ws
            wstool init src https://raw.githubusercontent.com/rosin-project/metacontrol_experiments/master/metacontrol_experiments.rosinstall
      - name: "Get dependencies"
        run: |
          sudo apt-get update
          rosdep update
          cd ~/metacontrol_ws          
          rosdep install --from-paths src --ignore-src -y --rosdistro=melodic --skip-keys="abb_rws_interface"
      - name: "Build"
        run: |
          cd ~/metacontrol_ws
          bash -i -c "source /opt/ros/melodic/setup.bash; catkin build"
      - name: "Run Scripts"
        run: |
          bash -i -c "source ~/metacontrol_ws/devel/setup.bash; \
          roscd metacontrol_experiments; \
          ps aux | grep ros | grep -v grep; \
          ./run_single_sim.sh -i ${{ matrix.init }} -g ${{ matrix.goal }} -n ${{ matrix.profile }}"
          find ${{ env.LOG_DIR }} -name "*.csv" -exec mv {} ${{ env.LOG_DIR }}/${{ env.LOG_FILENAME }}${{ matrix.profile }}
      - name: 'Upload log artifact'
        uses: actions/upload-artifact@v2
        with:
          name: log-artifact-${{ matrix.profile }}_${{ matrix.init }}_${{ matrix.goal }}
          path: ${{ env.LOG_DIR }}
